# Generated by Django 5.0.4 on 2024-04-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufactured_at',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='дата производства'),
        ),
    ]
