# Generated by Django 5.0.4 on 2024-04-29 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='version',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='catalog.product', verbose_name='продукт'),
        ),
        migrations.AlterField(
            model_name='version',
            name='version_number',
            field=models.PositiveIntegerField(default=0, verbose_name='номер версии'),
        ),
    ]
