# Generated by Django 4.2 on 2024-05-04 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name', 'price'], 'permissions': [('can_cancel_publish', 'Can cancel publish')], 'verbose_name': 'продукт', 'verbose_name_plural': 'продукты'},
        ),
    ]
